name: Export Traefik Tar
run-name: Exporting a tar file containing ready built traefik docs ğŸš€
on: [push]
jobs:
  Generate-Tar-File:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Display Docker version
        run: docker --version
      - name: Show dirs
        run: ls -lah
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build docker images
        working-directory: docs/
        run: DOCKER_BUILDKIT=1 docker build -f docs.Dockerfile -t traefik-docs:v1 .
      - name: save image as tar file
        run: docker save -o traefik-docs.tar traefik-docs:v1
      - name: Release the Tar Asset to Github
        uses: softprops/action-gh-release@v1
        with:
          draft: false  
          files: ${{ github.workspace }}/traefikdocs.tar
          name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          token: ${{ github.token }}